<?php 
include("admin-header.php");
if($_SESSION['ses_admin_id']==''){ echo'<script>window.location="index.php";</script>'; }
$refid=$_SESSION['ses_admin_id'];
error_reporting(0);
?>
<div class="contact-div">
    <div class="content">
	<?php include("admin-menu.php"); ?>
       <div class="offer-right-div">
        <div class="content-total-box">
           <h3 style="float:left;">Map View</h3>
		   <div style="float:right; margin:1%;">
		<?php 
		if(isset($_POST['submit'])){
			extract($_POST);
			echo"<script>window.location='admin-dashboard.php?driver=$driver';</script>";
		}
		if($_GET['driver']){ $driver=$_GET['driver']; }
		?>
		<form action="" method="post">
		<select name='driver'>
		<option <?php if($driver=="Available-Cabs"){ echo "selected='selected'"; } ?>>Available-Cabs</option>
		<option <?php if($driver=="Schedule-Cabs"){ echo "selected='selected'"; } ?>>Schedule-Cabs</option>
		</select>
		<input type="submit" value="Submit" name="submit" style="padding:0 10px; cursor:pointer;">
		</form>
		</div>
		<div class="clear"></div>
           <?php 
		if($_GET['driver']){
			$driver=$_GET['driver'];
			if($driver=="Schedule-Cabs"){ $sql=mysql_query("select * from driver_location where status='1' order by id asc"); }
			else{ $sql=mysql_query("select * from driver_location where status='0' and time > (now() - interval 3 minute) order by id asc"); }
		}
		else{
		$sql=mysql_query("select * from driver_location where status='0' and time > (now() - interval 3 minute) order by id asc");
		}
		if(mysql_num_rows($sql)==0){ echo "<div class='admin_faile'>Presently No Cabs found.</div>"; }
		else{
		?>
		<html>
<head>
<!--<meta http-equiv="refresh" content="30" />-->
<script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=places&sensor=false"></script>
<?php
$mrk_cnt = 0;	
while($re=mysql_fetch_array($sql)){
	$driver_id=$re['driver_id'];
	$driver_lat=$re['latitude'];
	$driver_lon=$re['longitude'];
	$driver_time=$re['time'];
	$driver_status=$re['status'];
	
	$sql1=mysql_query("select * from driver_reg where id='$driver_id'");
	$arr=mysql_fetch_array($sql1);
	$driver_name=$arr['driver_name']; 
	$driver_mobile=$arr['mobile'];
	$cab_id=$arr['cab_id'];
	$sql2=mysql_query("select * from cab_reg where id='$cab_id'");
	$arr2=mysql_fetch_array($sql2);
	$cab_number=$arr2['vehicle_reg'];
	$cab_type=$arr2['cartype'];
	
	$lat[] = $driver_lat;
	$lng[] = $driver_lon; 
	$driverid[] = $driver_id; 
	$start_time[] = $driver_date." ".$driver_time; 
	$name[] = $driver_name; 
	$mobile[] = $driver_mobile; 
	$cabmumber[] = $cab_number; 
	$cabtype[] = $cab_type; 
	$mrk_cnt++;
}
?>

<script type='text/javascript'>
var point;
var mrktx;
var latitude = null;
var longitude = null;


function initialize() {
   addTo = 0;
   var markers = [];
   //var latlng = new google.maps.LatLng("<?php echo $lat[0]; ?>","<?php echo $lng[0]; ?>");
   var latlng = new google.maps.LatLng("<?php echo $lat[0]; ?>","<?php echo $lng[0]; ?>");
   var myOptions = {
      zoom: 12,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
   };
   // NOTE: all values: latitude, longitude, zoom, etc.
   //       should also come from the database for flexibility
       
   var map = new google.maps.Map(document.getElementById("map"), 
              myOptions);
			
			  
// This next block of JavaScript needs to be generated by PHP 
// to 'add-in' the information from the arrays
var image = 'images/green.png';
<?php
for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++)
{
    echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
	 if($driver_status[$lcnt]=="1"){ 
	 $sql3=mysql_query("select * from trip_reg where driver_id='$driverid[$lcnt]' and status='0' order by id desc");
	 $arr3=mysql_fetch_array($sql3);
	 $trip_id=$arr3['id'];
	 $link="<a href='admin-view-map.php?id=$trip_id' style='color:#333; text-decoration:none;'>"; $link1="</a>"; } else{ $link=""; $link1=""; }
    echo "var mrktx$lcnt = \"$link<span style='font-size: 12px; text-align:center; display:block;'>Time: $start_time[$lcnt]<br>Driver Name: $name[$lcnt]<br>Mobile: $mobile[$lcnt]<br>Cab No: $cabmumber[$lcnt]<br>Cab Type: $cabtype[$lcnt]</span>$link1\";\n";
	echo "var infowindow$lcnt = new google.maps.InfoWindow({
   			content: mrktx$lcnt
			});";
	if($driver=="Schedule-Cabs"){ echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt, map: map});\n"; }
	else{ echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt, map: map, icon: image});\n"; }
	echo "google.maps.event.addListener(marker$lcnt, 
         'mouseover', function() {
   		     infowindow$lcnt.open(map,marker$lcnt);
          });\n";
	echo "google.maps.event.addListener(marker$lcnt, 
         'mouseout', function() {
   		     infowindow$lcnt.close();
          });\n";
}
?>

	//Create the search box and link it to the UI element.
	var input =document.getElementById('pac-input');
   
	map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

	var searchBox = new google.maps.places.SearchBox((input));

	// [START region_getplaces]
	  // Listen for the event fired when the user selects an item from the
	  // pick list. Retrieve the matching places for that item.
	  google.maps.event.addListener(searchBox, 'places_changed', function() {
	    var places = searchBox.getPlaces();
	    map.setZoom(40);
	    if (places.length == 0) {
	      return;
	    }
	    for (var i = 0, marker; marker = markers[i]; i++) {
	      marker.setMap(null);
	    }

	    // For each place, get the icon, place name, and location.
	    markers = [];
	    var bounds = new google.maps.LatLngBounds();
	    for (var i = 0, place; place = places[i]; i++) {
	      var image = {
	        url: place.icon,
	        size: new google.maps.Size(71, 71),
	        origin: new google.maps.Point(0, 0),
	        anchor: new google.maps.Point(17, 34),
	        scaledSize: new google.maps.Size(25, 25)
	      };

	      // Create a marker for each place.
	      var marker = new google.maps.Marker({
	        map: map,
	        icon: image,
	        title: place.name,
	        position: place.geometry.location
	      });

	      markers.push(marker);

	      bounds.extend(place.geometry.location);
	    }

	    map.fitBounds(bounds);
	  });
	  // [END region_getplaces]

	// Bias the SearchBox results towards places that are within the bounds of the
	  // current map's viewport.
	  google.maps.event.addListener(map, 'bounds_changed', function() {
	    var bounds = map.getBounds();
	    searchBox.setBounds(bounds);
	    
	  });
}
google.maps.event.addDomListener(window, "load", initialize);
</script>
	
	
</head>
<body >	
			<input id="pac-input" class="controls" type="text" placeholder="Search Box">		
			<div id="map" class="map" style="height: 460px; margin: 1%; border: 1px solid #ccc;">
				
			</div>
			
</body>
</html>	
        <?php } ?>
		 <div class="clear"></div>
         </div>
      </div>
      <style>
      	 #pac-input {
	        background-color: #fff;
	        font-family: Roboto;
	        font-size: 15px;
	        font-weight: 300;
	        margin-left: 12px;
	        padding: 0 11px 0 13px;
	        text-overflow: ellipsis;
	        width: 400px;
     	 }

	      #pac-input:focus {
	        border-color: #4d90fe;
	      }
      	
      </style>
	  <?php include("admin-footer.php"); ?>
       